name: Publish to Google Play

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: "Publish to Google Play"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ORG_GRADLE_PROJECT_FILM_TIME_TMDB_API_KEY: ${{ secrets.FILM_TIME_TMDB_API_KEY }}
      ORG_GRADLE_PROJECT_FILM_TIME_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.FILM_TIME_RELEASE_KEYSTORE_PASSWORD }}
      ORG_GRADLE_PROJECT_FILM_TIME_RELEASE_KEY_PASSWORD: ${{ secrets.FILM_TIME_RELEASE_KEY_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Check build-logic
      run: ./gradlew check -p ./gradle/build-logic

    - name: Decrypt secrets
      run: ./release/decrypt-secrets.sh
      env:
        ENCRYPT_KEY: ${{ secrets.FILM_TIME_CI_ENCRYPT_KEY }}

    - name: Publish to Google Play
      run: ./gradlew publishGooglePlayReleaseBundle --no-daemon

    - name: Clean secrets
      if: always()
      run: ./release/clean-secrets.sh
